spring:
  datasource:
    password: root
    url: jdbc:mysql://localhost:3306/benk?serverTimezone=UTC
    username: root
  security:
    csrf:
      enabled: false  
logging:
  level:
    org.springframework.security.web: DEBUG
